ase_project/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('homepage/',include('django.contrib.auth.urls')),
    path('',views.index,name='index'),
    path('homepage/',include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('finalapp/',include('finalapp.urls')),
    path('category_page/',include('category_page.urls')),
    path('myapp',include('myapp.urls')),
    path('feedback/',views.display_feedback,name='display_feedback')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalapp/urls.py
from django.urls import path, re_path
from . import views
app_name='finalapp'
urlpatterns = [
    path('',views.home,name="home"),
    path('upload/',views.model_form_upload,name='model_form_upload'),
    path('searchdata/',views.searchdata,name='searchdata'),
    path('api/',views.DocumentListView.as_view())
]

homepage/urls.py
from django.urls import path
from homepage import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
app_name='homepage'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('password_reset/',PasswordResetView.as_view(),name="password_reset"),
    path('password_reset_done/',PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password_reset_confirm/',PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('feedback/',views.user_feedback,name="user_feedback"),

    path('profile_view/',views.profile_view,name="profile_view"),
    path('delete_image/(?P<value>\s+)',views.delete_image,name="delete_image"),
    path('edit_profile/',views.edit_profile,name="edit_profile"),
    path('update_image/(?P<value>\s+)',views.update_image,name="update_image"),


]

myapp/urls.py
from django.urls import path
from myapp import views


app_name='myapp'

urlpatterns=[
     path('index/(?P<value>\s+)',views.index,name='index'),
    path('category',views.category,name='category'),
    path('likes/(?P<imageid>\s+)',views.countlikes,name='countlikes'),
     path('user/(?P<value>\s+)',views.user,name='user'),
    path('logout/', views.user_logout, name='logout'),

]

homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)
    bio=models.CharField(max_length=250,default="x")
    city=models.CharField(max_length=80,default="x")
    phone=models.IntegerField(max_length=12,default=12345)

    user=models.ForeignKey(User,on_delete='PROTECT')


    def __str__(self):
        return self.user.username
class feedback(models.Model):
    name=models.CharField(max_length=250)
    rating=models.CharField(max_length=2)
    text=models.CharField(max_length=250)


    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from homepage.models import UserProfileInfo,feedback
from django.contrib import messages

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    re_password=forms.CharField()
    class Meta():
        model=User
        fields=('username','first_name','last_name','email','password')
    def clean(self):
        all_clean_data=super().clean()
        username=all_clean_data['username']
        email=all_clean_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
class FeedbackForm(forms.ModelForm):
    class Meta():
        model=feedback
        fields=('name','rating','text')

homepage/views.py
from django.shortcuts import render
from homepage.forms import UserForm,FeedbackForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django import forms
from django.contrib import messages
from homepage.models import feedback
from django.shortcuts import redirect
from finalapp.models import Document
from homepage.models import UserProfileInfo
def index(request):
    my_list=Document.objects.order_by('-pk')

    my_dict={'new_images':my_list}

    return render(request,'homepage/index.html',my_dict)



def register(request):
    registered=False

    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        re_password=request.POST.get('re_password')
        password=request.POST.get('password')
        print(password,"\n",re_password)
        if re_password==password:
            if user_form.is_valid():
                user=user_form.save()
                user.set_password(user.password) #hashing the password
                user.save() #save hash password to database
                registered=True
            else:
                print("something is fishy")
        else:

            raise forms.ValidationError("Passwords do not match.Please Re_enter them")

            raise forms.ValidationError("Passwords do not match")

    else:
        user_form=UserForm()

    return render(request,'homepage/registration.html',{'user_form':user_form,'registered':registered,})

@login_required
def special(request):
    return HttpResponse("You are logged in dude")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("someone tried to login and failed")
            print("username:{} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'homepage/login.html')
def user_feedback(request):
    if request.method=="POST":
        feedback_form=FeedbackForm(data=request.POST)
        if feedback_form.is_valid():
            feedback=feedback_form.save()
            feedback.save()
            print(feedback_form.cleaned_data['text'])
        return HttpResponseRedirect(reverse('index'))
    return render(request,'homepage/feedback.html')
def display_feedback(request):
    feedbacks=feedback.objects.order_by('-pk')

    sum=0
    count=0
    for i in feedbacks:
        sum=sum+int(i.rating)
        count=count+1
    avg_rating=sum/count
    print(sum)
    print(avg_rating)
    my_dict={'feedbacks':feedbacks,'avg_rating':avg_rating}
    return render(request,'homepage/display_feedbacks.html',my_dict)

def profile_view(request):

    info_object,created = UserProfileInfo.objects.get_or_create(user=request.user)
    user_name=request.user.username
    print(user_name)
    images=Document.objects.filter(user=request.user)
    my_dict = {'user': user_name, 'images': images, 'bio': info_object.bio, 'phone': info_object.phone,'city': info_object.city}
    return render(request,'homepage/user_profile.html', my_dict)
def delete_image(request,value):
    Document.objects.filter(name=value).delete()

    info_object,created = UserProfileInfo.objects.get_or_create(user=request.user)
    user_name=request.user.username
    print(user_name)
    images=Document.objects.filter(user=request.user)
    my_dict = {'user': user_name, 'images': images, 'bio': info_object.bio, 'phone': info_object.phone,'city': info_object.city}
    return render(request,'homepage/user_profile.html', my_dict)
def edit_profile(request):
    if request.method=="POST":
        bio=request.POST.get('bio')
        phone=request.POST.get('phone')
        city=request.POST.get('city')
        user=request.user
        info_object,created=UserProfileInfo.objects.get_or_create(user=user)
        info_object.bio=bio
        info_object.phone=phone
        info_object.city=city
        info_object.save()

        user_name = request.user.username
        print(user_name)
        images = Document.objects.filter(user=request.user)
        my_dict = {'user': user_name, 'images': images,'bio':info_object.bio,'phone':info_object.phone,'city':info_object.city}
        return render(request, 'homepage/user_profile.html', my_dict)
    return render(request,'homepage/edit_profile.html')

def update_image(request,value):
    if request.method=="POST":
        name=request.POST.get('name')
        category=request.POST.get('category')
        image_info_object=Document.objects.get(name=value)
        image_info_object.name=name
        image_info_object.category=category
        image_info_object.save()
        return redirect(reverse('homepage:profile_view'))

    return render(request,'homepage/update_image.html',{'name':value})

templates/homepage/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <!--Links for materialize css-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

      <!-- font awesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title></title>
  <!--links for fonts-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

  </head>
  <body style="font-family: 'Poppins', sans-serif;">

      <div class="navbar-fixed">
        <nav class="nav-wrapper transparent blue-grey darken-3">
          <div class="container">
            <a href="{%url 'index' %}" class="brand-logo" style="font-family: 'Montserrat', sans-serif;">Free Stock</a>
            <a href="#" class="sidenav-trigger" data-target="mobile-links">
              <i class="material-icons">menu</i>
            </a>

            <ul class="right hide-on-med-and-down valign-wrapper">
              <li>
                <div style="height:3vw" >
                <form action="{% url 'finalapp:searchdata' %}" method="get">
                <div class="input-field grey lighten-4">
                    <input id="search" name="searchword" type="search" required>
                    <label class="label-icon valign-wrapper" for="search"><i class="material-icons indigo-text text-darken-4">search</i></label>
                    <i class="material-icons">close</i>
                </div>
                </form>
              </li>


              {% if request.user.is_authenticated %}
              <li>
                <a href="{% url 'homepage:profile_view' %}" >Profile</a>
              </li>
              <li>
                <a href="{% url 'logout' %}" >Logout</a>
              </li>
              {% else %}
              <li>
                <a href="{% url 'homepage:user_login' %}">Login</a>
              </li>

              <li>
                  <a href="{% url 'homepage:register' %}">Signup</a>
              </li>

              {% endif %}



              <li>
                <a href="#about">About</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>

      <ul class="sidenav" id="mobile-links">
        <div class="container">

          <li>
            <form action="{% url 'finalapp:searchdata' %}" method="get">
            <div class="input-field">
                <input id="search" type="search" name="searchword" placeholder="Search images" required>
                <i class="material-icons">close</i>
            </div>
            </form>
          </li>
        </div>


        {% if request.user.is_authenticated %}
        <li>
          <a href="{ % url 'homepage:profile_view' % }" >Profile</a>

        </li>
        <li>
          <a href="{% url 'logout' %}" >Logout</a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'homepage:user_login' %}">Login</a>
        </li>
        <li>
          <a href="{% url 'homepage:register' %}">Signup</a>
        </li>
        {% endif %}

        <li>
          <a href="#about" >About</a>
        </li>

      </ul>





      <!-- Compiled and minified JavaScript -->
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
      <script>
        $(document).ready(function(){
          $('.sidenav').sidenav();
          $('.scrollspy').scrollSpy();
        });
      </script>





      <div >
        {% block content %}
        {% endblock %}
      </div>

              <footer class="page-footer scrollspy blue-grey darken-4" id="about">
                <div class="container ">
                  <div class="row">
                    <div class="col l6 s12">
                      <h5 class="white-text">About</h5>

                      <p class="grey-text text-lighten-4">FreeStock.com is a website where a user can download free stock photos. <br><br>

                      <p class="grey-text text-lighten-4">FreeStock.com is a website where a user can download free stock photos <br>

                        A user can also join our community by signing up and posting their photographs.This is how our site works.
                      </p>
                    </div>
                    <div class="col l4 offset-l2 s12">
                      <h5 class="white-text">Contact</h5>
                      <ul>

                        <li><a class="white-text text-ighten-3" href="#!">Gmail</a></li>
                        <li><a class="white-text text-lighten-3" href="#!">Facebook</a></li>
                        <li><a class="white-text text-lighten-3" href="#!">Instagram</a></li>
                        <li><a class="white-text text-lighten-3" href="{% url 'homepage:user_feedback' %}">Feedback</a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="footer-copyright">
                    <div class="container">
                    © 2018 FreeStock.Com
                    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
                    </div>
                  </div>
                </div>
              </footer>

  </body>
</html>

templates/homepage/display_feedbacks.html
{% extends "homepage/base.html" %}
{% block content %}

        <div class="row">
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Total Rating : {{ avg_rating }} / 10</span>
          </div>
        </div>
      </div>
    </div>

<ol>
  {% for item in feedbacks %}

    <div class="row">
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">{{item.name}}:{{item.rating}}</span>
            <p>{{item.text}}</p>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</ol>

<ol>



{% load staticfiles %}

{% endblock %}

templates/homepage/edit_profile.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
<div class="row">
<form class="col s12" method="POST" action="{% url 'homepage:edit_profile' %}" name="user_feedback" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="city" type="text" class="validate" name="city" required>
      <label for="city">City</label>
    </div>
  </div>


  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="phone" type="number" class="validate" name="phone" min="1" max="999999999999" required>
      <label for="phone">Contact Number</label>
    </div>
  </div>
  <div class="row">
    <div class=" col s5 offset-s4">
    <textarea name="bio" rows="8" cols="80"></textarea>
      <label for="bio">Your Bio</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s4 offset-s5">
      <button class="  btn waves-effect waves-light" type="submit" name="submit">Submit
     </button>
    </div>
  </div>

</form>
</div>
{% endblock %}

templates/homepage/feedback.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
<div class="row">
<form class="col s12" method="POST" action="{% url 'homepage:user_feedback' %}" name="user_feedback" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="name" type="text" class="validate" name="name" required>
      <label for="name">Name</label>
    </div>
  </div>


  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="rating" type="number" class="validate" name="rating" min="1" max="10" required>
      <label for="rating">Rating out of 10</label>
    </div>
  </div>
  <div class="row">
    <div class=" col s5 offset-s4">
    <textarea name="text" rows="8" cols="80"></textarea>
      <label for="text">Your Review</label>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s4 offset-s5">
      <button class="  btn waves-effect waves-light" type="submit" name="submit">Submit
     </button>
    </div>
  </div>

</form>
</div>
{% endblock %}

templates/homepage/index.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}

{% load mytags %}

<!--Slider-->
  <div class="slider">
    <ul class="slides">
      <li>
        <img  src="{% static 'homepage/images/slider1.jpeg'%}"> <!-- random image -->
        <div class="caption center-align">
          <h3>Welcome!</h3>
          <h5 >To The Rapidly Growing Community</h5>
        </div>
      </li>
      <li>
        <img  src="{% static 'homepage/images/slider2.jpeg'%}"> <!-- random image -->
        <div class="caption left-align " >
          <h3>Download From The Millions Of Stock Images</h3>
          <h5 >And It's Free!</h5>
        </div>
      </li>
      <li>
        <img src="{% static 'homepage/images/slider3.jpeg'%}"> <!-- random image -->
        <div class="caption right-align">
          <h3>Become A Contributer</h3>
          <h5 >Show Your Skills</h5>
        </div>
      </li>
    </ul>
  </div>
<!--push and pull-->
<section class="container section" id="photos" style="padding-top:4vw;padding-bottom:4vw;">
  <div class="row">
    <div class="col s12 l4">
        <img src="{% static 'homepage/images/journey.jpeg'%}" alt="" class="responsive-img materialboxed">
    </div>
    <div class="col s12 l6 offset-l1">
      <h2 class="blue-grey-text text-darken-3">Contribute</h2>
      <p>Contribute by uploading your photographs and showcase your amazing photography skills</p>
    </div>
  </div>
  <div class="row">
    <div class="col s12 l4 offset-l1 push-l7">
        <img src="{% static 'homepage/images/portrait.jpg'%}" alt="" class="responsive-img materialboxed">
    </div>
    <div class="col s12 l6 offset-l1 pull-l5 right-align">
      <h2 class="blue-grey-text text-darken-3">Search</h2>
      <p>Search from the millions of images in our collection</p>
      <nav>
      <div class="nav-wrapper">
        <form action="{% url 'finalapp:searchdata' %}" method="get">
          <div class="input-field grey lighten-4">
            <input id="search" type="search" name="searchword" required>
            <label class="label-icon" for="search"><i class="material-icons indigo-text text-darken-4">search</i></label>
            <i class="material-icons">close</i>
          </div>
        </form>
      </div>
      </nav>
    </div>
  </div>

</section>
<!--Parallax-->

    <div class="parallax-container" style="height:25vw;">
      <div class="parallax responsive-img"><img src="{% static 'homepage/images/parallax.jpeg'%}"></div>
    </div>

<!--carousel-->
<div class="container">
<p >
  <h3 class="center-align blue-grey-text text-darken-3"> Popular Categories</h3>
</p>

  <div class="carousel">

    <a class="carousel-item" href="{% url 'myapp:index' value="Animals" %}">
        <img src="{% static 'homepage/images/animals.jpg' %}">
        <p ><h5 class="center-align black-text flow-text">Animals</h5></p>
    </a>



    <a class="carousel-item"  href="{% url 'myapp:index' value="Abstract" %}">

        <img src="{% static 'homepage/images/abstract.jpg'%}">
        <p ><h5 class="center-align black-text flow-text">Abstract</h5></p>
    </a>



    <a class="carousel-item"  href="{% url 'myapp:index' value="Festivals" %}">

        <img src="{% static 'homepage/images/festivals.jpg'%}">
        <p ><h5 class="center-align black-text flow-text">Festivals</h5></p>
    </a>

]

    <a class="carousel-item"  href="{% url 'myapp:index' value="Food" %}">

        <img src="{% static 'homepage/images/food.jpg'%}">
        <p ><h5 class="center-align black-text flow-text">Food</h5></p>
    </a>


    <a class="carousel-item"  href="{% url 'myapp:index' value="Lifestyle" %}">

        <img src="{% static 'homepage/images/lifestyle.jpg'%}">
        <p ><h5 class="center-align black-text flow-text">Lifestyle</h5></p>
    </a>




    <a class="carousel-item"  href="{% url 'myapp:index' value="Nature" %}">

        <img src="{% static 'homepage/images/nature.jpg'%}">
        <p ><h5 class="center-align black-text flow-text">Nature</h5></p>
    </a>




    <a class="carousel-item"  href="{% url 'myapp:index' value="People" %}">

        <img src="{% static 'homepage/images/people.jpg'%}">
        <p ><h5 class="center-align black-text flow-text">People</h5></p>
    </a>




    <a class="carousel-item"  href="{% url 'myapp:index' value="Objects" %}">

        <img src="{% static 'homepage/images/objects.jpg'%}">
        <p ><h5 class="center-align black-text flow-text">Objects</h5></p>
    </a>
  </div>

</div>

<!--parallax2-->
<div class="parallax-container" style="height:25vw;">
  <div class="parallax responsive-img"><img src="{% static 'homepage/images/parallax1.jpeg'%}"></div>
</div>

<!--New Arrivals-->
<div class="container">
<p >
  <h3 class="center-align blue-grey-text text-darken-3"> New Arrivals</h3>
</p>

  <div class="carousel">

    {% for image in new_images %}

    <div class="carousel-item valign-wrapper">
      <img id="id{{ forloop.counter }} onclick="popup('myModal', 'id{{ forloop.counter }}', 'img01', 'download_img', '{{ image.image.url }}')"
       src="{{ image.image.url }}" alt="">

    </div>

    {% endfor %}



  </div>

</div>


  <script>

  $(document).ready(function(){
    $('.slider').slider({
      duration:500,
      interval:3000,
      indicators:false,
    });
     $('.materialboxed').materialbox();
     $('.parallax').parallax();
      $('.carousel').carousel();
  });

  </script>

{% endblock %}

templates/homepage/login.html
{% extends 'homepage/base.html' %}
{% block content %}
<div class="row">
<form class="col s12" method="POST" action="{% url 'homepage:user_login' %}" name="user_login" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="username" type="text" class="validate" name="username" required>
      <label for="username">User Name</label>
    </div>
  </div>


  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="password" type="password" class="validate" name="password" required>
      <label for="password">Password</label>
    </div>
  </div>
  <div class="row">
    <div class=" col s2 offset-s5">
      <a href="{% url 'homepage:password_reset' %}">Forgot Password?</a>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s4 offset-s5">
      <button class="  btn waves-effect waves-light" type="submit" name="submit">Submit
     </button>
    </div>
  </div>

</form>
</div>



{% endblock %}

templates/homepage/registration.html
{% extends "homepage/base.html" %}
{% load staticfiles %}
{% block content %}
{% if user_form.errors %}
    {% for field in user_form %}
        {% for error in field.errors %}
              <div class="container center-align">
                <h5>{{error|escape}}<h5>
              </div>
        {% endfor %}
    {% endfor %}
    {% for error in user_form.non_field_errors %}
    <div class="container center-align">
      <h5>{{error|escape}}<h5>
    </div>
    {% endfor %}
{% endif %}
   {% if registered %}
      <div class="container center-align">
        <h2>Thank You For Being A Collaborator</h3>
        <h3>Your account has been activated</h3>
        <p>
          <span>  <a class="btn"href="{% url 'homepage:user_login'%}">Click Here</a>
          </span>to Login

        </p>

      </div>
   {% else %}

  <div class="row">
  <form class="col s12" method="POST" name="user_form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <div class="input-field col s4 offset-s2">
        <input  id="first_name" type="text" class="validate" name="first_name" required>
        <label for="first_name">First Name</label>
      </div>
      <div class="input-field col s4">
        <input id="last_name" type="text" class="validate" name="last_name">
        <label for="last_name">Last Name</label>
      </div>
    </div>
    <div class="row">
    <div class="input-field col s4 offset-s2">
      <input id="username" type="text" class="validate" name="username" required>
      <label for="username">User Name</label>
    </div>


      <div class="input-field col s4">
        <input id="password" type="password" class="validate" name="password" min="6" required>
        <label for="password">Password</label>
      </div>
    </div>


    <div class="row">
      <div class="input-field col s4 offset-s2">
        <input id="email" type="email" class="validate" name="email" required>
        <label for="email">Email</label>
      </div>
      <div class="input-field col s4">
          <input id="re_password" type="password" class="validate" name="re_password" min="6" required>
          <label for="re_password">Retype Password</label>
      </div>

    </div>
    <div class="row">
      <div class="input-field col s4 offset-s5">
        <button class="  btn waves-effect waves-light" type="submit" name="submit">Submit
       </button>
      </div>

    </div>

  </form>
</div>


   {% endif %}

{% endblock %}

templates/homepage/update_image.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}
<div class="row">
<form class="col s12" method="POST" action="{% url 'homepage:update_image'  value=name %}" name="user_feedback" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="name" type="text" class="validate" name="name" required>
      <label for="name">Image Name</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s4 offset-s4">
      <input id="category" type="text" class="validate" name="category" required>
      <label for="category">New Category</label>
    </div>
  </div>



  <div class="row">
    <div class="input-field col s4 offset-s5">
      <button class="  btn waves-effect waves-light" type="submit" name="submit">Submit
     </button>
    </div>
  </div>

</form>
</div>
{% endblock %}

templates/homepage/user_profile.html
{% extends "homepage/base.html" %}
{% block content %}
{% load staticfiles %}

<h1 class="center-align">Welcome {{ user }}</h1>
<br>
<ol>

    <div class="row">
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Details</span>
              <p><b>Name: {{ user }} <br>Bio: {{ bio }} <br>Contact Number : {{ phone }}<br>City : {{ city }}</b></p>
          </div>
        </div>
      </div>
    </div>

</ol>
<h3>Here are your uploaded images</h3><br>
    <a class=" btn" href="{% url 'finalapp:model_form_upload' %}">Upload NEW </a><br><br>
        <a class=" btn" href="{% url 'homepage:edit_profile' %}">Edit Profile </a><br><br>
<div class="row">
{% for image in images %}

    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-image">
          <img src="{{ image.image.url }}">
          <span class="card-title">{{ image.name }}</span>
          <a  href="{% url 'homepage:delete_image' value=image.name %}" title="delete" class="btn-floating halfway-fab waves-effect waves-light blue-grey darken-3"><i class="material-icons">close</i></a>
        </div>
        <div class="card-content">
          <p>Name : {{ image.name }} <br> Category : {{ image.category }}</p>
          <a  href="{% url 'homepage:update_image' value=image.name %}" title="Edit Image" class="btn-floating  waves-effect waves-light blue-grey darken-3"><i class="material-icons">add</i></a>

        </div>
      </div>
    </div>
{% endfor %}
</div>


{% endblock %}