ase_project/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('homepage/',include('django.contrib.auth.urls')),
    path('',views.index,name='index'),
    path('homepage/',include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('finalapp/',include('finalapp.urls')),
    path('category_page/',include('category_page.urls')),
    path('myapp',include('myapp.urls')),
    path('feedback/',views.display_feedback,name='display_feedback')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalapp/urls.py
from django.urls import path, re_path
from . import views
app_name='finalapp'
urlpatterns = [
    path('',views.home,name="home"),
    path('upload/',views.model_form_upload,name='model_form_upload'),
    path('searchdata/',views.searchdata,name='searchdata'),
    path('api/',views.DocumentListView.as_view())
]

myapp/urls.py
from django.urls import path
from myapp import views


app_name='myapp'

urlpatterns=[
     path('index/(?P<value>\s+)',views.index,name='index'),
    path('category',views.category,name='category'),
    path('likes/(?P<imageid>\s+)',views.countlikes,name='countlikes'),
     path('user/(?P<value>\s+)',views.user,name='user'),
    path('logout/', views.user_logout, name='logout'),

]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('register/', views.register, name='register'),
    path('profile/',views.profile, name='profile'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

]

myapp/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300 ,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

myapp/views.py
from django.shortcuts import render, redirect
from finalapp.models import Document,LikedUser
from django.http import HttpResponse
from django.contrib.auth import logout
import os
from django.conf import settings

# Create your views here.
#import pathlib
def index(request,value):
    p=Document.objects.filter(category=value)
    items=[]
    listitems=[]

    context={'items':p}
    return render(request, 'myapp/category/index.html', context)


def user(request,value):
    p = Document.objects.filter(user=value)
    print(Document.objects.filter(user=value))
    context={'items':p}
    return render(request, 'myapp/category/user.html', context)


def countlikes(request,imageid):
    liked_photos = None
    if request.method=='GET':
        try:
            liked_photos = LikedUser.objects.filter(user=request.user.username)

        except:
            pass

        if imageid:
            likedata=Document.objects.get(image=imageid)
            if liked_photos is not None:
                liked_images_list = []
                for entry in liked_photos:
                    liked_images_list.append(entry.image)
                if likedata.image.url in liked_images_list:
                    return HttpResponse("You've already liked this photo.")

            LikedUser.objects.create(user=request.user.username, image=likedata.image.url)
            pre_likes = likedata.likes
            pre_likes += 1
            likedata.likes = pre_likes
            likedata.save()
    return HttpResponse('you have liked the image...please go back for more images')


def category(request):
    return render(request,'myapp/category/category.html')

def user_logout(request):
    logout(request)
    return redirect('finalapp:home')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'users/profile.html')

templates/myapp/category/index.html
{% load staticfiles %}
<html>
   <head>
      <title>Freestock</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
         integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
         integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
         integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <script src="{% static 'category/scripts/script.popup.js' %}"></script>
      <link href="{% static 'category/css/layout.css' %}"  rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'category/css/layouteffects.css' %}"  rel="stylesheet" type="text/css" media="all">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
         integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'category/css/new01.css' %}">
      <link rel="shortcut icon" href="{% static 'category/images/favicon.ico' %}" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">





   </head>
   <body id="top">
      <div class="bgded overlay" style="background-color:#546e7a;">
         <div class="wrapper row0">
            <div id="topbar" class="hoc clear">
               <div class="fl_right">
                  <ul class="nospace">
                     <li>Hi!</li>
                  </ul>
               </div>
            </div>
         </div>
         <div class="wrapper row1">
            <header id="header" class="hoc clear">
               <div id="logo" class="fl_left">
                  <h1><a href="{% url 'index' %}">Freestock</a></h1>
               </div>
               <form class="example rounded" method="get" action="{% url 'finalapp:searchdata' %}" style="margin-left:275px;margin-top:20px;max-width:400px">
               {%  csrf_token %}
               <input type="text" placeholder="Search.." name="searchword">
               <button type="submit"><i class="fa fa-search"></i></button>
               </form>
               <nav id="mainav" class="fl_right">
                  <ul class="clear">
                     <li><a href="{% url 'index' %}">Home</a></li>
                     <li><a href="#">About</a></li>
                     <li class="active">
                        <a class="drop" href="#">Categories</a>
                        <ul>
                           <li><a href="#">Fashion</a></li>
                           <li><a href="#">Nature</a></li>
                           <li><a href="#">Wildlife</a></li>
                           <li><a href="#">Sports</a></li>
                           <li><a href="{% url 'myapp:category' %}">+More</a></li>
                        </ul>
                     </li>
                  </ul>
               </nav>
            </header>
         </div>
      </div>
      <div class="wrapper row2">
         <div id="breadcrumb" class="hoc clear">
            <ul>
               <li><a href="{% url 'index' %}">Home</a></li>
               <li><a href="{% url 'myapp:category' %}">Categories</a></li>
               <li><a href="#">Search</a></li>
            </ul>
         </div>
      </div>
      <div class="wrapper row3">
         <main class="hoc container clear">
            <div class="content">
               <p style="font-family:verdana;font-size:25px">Search results {{value}}</p>
               <!-- ===================================Photo Grids ============================ -->
               <div class="container mt-5" style="text-align: center">
                <div class="row">
                    {% for item in items %}
                    <div class="col-md-3 mt-5">
                        <img src="{{ item.image.url }}" alt="{{item.user}}" class="image" id="id{{ forloop.counter }}" name="img{{ forloop.counter }}"
                             onclick="popup('myModal', 'id{{ forloop.counter }}', 'img01', 'download_img', '{{ item.image.url }}','user',
                                             '{% url 'myapp:countlikes' item.image %}','li',
                                              '{% url 'myapp:user' item.user.id %}', '{{ item.likes }}')">
                    </div>
                    {% endfor %}

                </div>
            </div>

            <div id="myModal" class="container modal" style="width: 100%; height: 100%;">

                <div class="row">
                    <div class="col-md-8">
                        <img class="modal-content" id="img01">
                    </div>
                    <span class="close">&times</span>
                    <div class="col-sm-4">
                        <div class="btn-group-vertical">
                                <button class="btn btn-success">
                                    <a id="download_img" style="color: black; text-decoration: none" download>
                                        Free Download
                                    </a>
                                </button>

                            <br>
                            <form id="li" method="get">
                                {% if user.is_authenticated %}
                                <button class="btn btn-success">
                                    <span class="glyphicon glyphicon-thumbs-up"></span>
                                    Like &nbsp
                                    <span id="likes"></span>
                                </button>
                                {% else %}
                                <button class="btn btn-success"  disabled><span class="glyphicon glyphicon-thumbs-up"></span> Like</button><br>
                                <p>please login to like</p>
                                {% endif %}
                            </form><br>
                            <p style="color:#7FFF00"> image by:
                                <a id="user"></a>
                            </p>
                        </div><br><br>


                        <p style="color:#7FFF00">Freestock License:</p>
                        <p><span class="glyphicon glyphicon-ok"></span>  free for personal and commercial use</p>
                        <p><span class="glyphicon glyphicon-ok"></span> You can modify the photos.</p>

                        <div class="col-xs-6>
                            <div class="follow" style="color:#7FFF00">Follow us:</div>
                            <ul class="faico clear">
                              <li><a class="fa fa-facebook-official" href="#"><i></i></a></li>
                              <li><a class="fa fa-instagram"  href="#"><i></i></a></li>
                              <li><a class="fa fa-twitter-square" href="#"><i></i></a></li>
                              <li><a class="fa fa-google-plus-square" href="#"><i></i></a></li>
                            </ul>
                        </div>

                    </div>

                </div>
            </div>
<!------------------------------------------------------------------------------------------------------------------------->
               <nav class="pagination">
                  {% if users.has_other_pages %}
                  <ul style="margin-left: 28%;">
                     {% if users.has_previous %}
                     <li><a href="?page={{ users.previous_page_number }}">&laquo; Previous</a></li>
                     {% else %}
                     <li class="disabled"></li>
                     {% endif %}
                     {% for i in users.paginator.page_range %}
                     {% if users.number == i %}
                     <li class="current"><strong>{{ i }}</strong></li>
                     {% else %}
                     <li><a href="?page={{ i }}">{{ i }}</a></li>
                     {% endif %}
                     {% endfor %}
                     {% if users.has_next %}
                     <li><a href="?page={{ users.next_page_number }}">Next &raquo;</a></li>
                     {% else %}
                     <li class="disabled"></li>
                     {% endif %}
                  </ul>
                  {% endif %}
               </nav>
            </div>
            <div class="clear"></div>
         </main>
      </div>
      <div class="wrapper row4 bgded overlay" style="background-color:#546e7a;">
        <footer id="footer" class="hoc clear">
          <div class="one_third first">
            <h6 class="title">CONTACT</h6>
            <ul class="faico clear">
              <li><a class="fa fa-facebook-official" href="#"><i></i></a></li>
              <li><a class="fa fa-instagram"  href="#"><i></i></a></li>
              <li><a class="fa fa-twitter-square" href="#"><i></i></a></li>
              <li><a class="fa fa-google-plus-square" href="#"><i></i></a></li>
            </ul>
          </div>
          <div class="one_third">
            <h6 class="title"></h6>
            <ul class="nospace linklist contact">
                    </ul>
          </div>
          <div class="one_third">
            <h6 class="title">Freestock.com</h6>
            <ul class="nospace linklist">
              <li>
                <article>
                  <h2 class="nospace font-x1"><a href="#">About</a></h2>
                  <p class="nospace">FreeStock.com is a website where a user can download free stock photos </p>
                </article>
              </li>
            </ul>
          </div>
        </footer>
      </div>
      <div class="wrapper row5">
        <div id="copyright" class="hoc clear">
          <p class="fl_left">Copyright &copy; 2018 - All Rights Reserved - <a href="#">freestock.com</a></p>
          </div>
      </div>
      <a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>


      <script src="{% static 'category/scripts/jquery.min.js' %}"></script>
      <script src="{% static 'category/scripts/jquery.backtotop.js' %}"></script>
      <script src="{% static 'category/scripts/jquery.mobilemenu.js' %}"></script>
   </body>
</html>

templates/myapp/category/user.html
{% load staticfiles %}
<html>
   <head>
      <title>Freestock</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
         integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
         integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
         integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <script src="{% static 'category/scripts/script.popup.js' %}"></script>
      <link href="{% static 'category/css/layout.css' %}"  rel="stylesheet" type="text/css" media="all">
      <link href="{% static 'category/css/layouteffects.css' %}"  rel="stylesheet" type="text/css" media="all">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
         integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'category/css/new01.css' %}">
      <link rel="shortcut icon" href="{% static 'category/images/favicon.ico' %}" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">





   </head>
   <body id="top">
      <div class="bgded overlay" style="background-color:#546e7a;">
         <div class="wrapper row0">
            <div id="topbar" class="hoc clear">
               <div class="fl_right">
                  <ul class="nospace">
                     <li>Hi!</li>
                  </ul>
               </div>
            </div>
         </div>
         <div class="wrapper row1">
            <header id="header" class="hoc clear">
               <div id="logo" class="fl_left">
                  <h1><a href="{% url 'index' %}">Freestock</a></h1>
               </div>
               <form class="example rounded" method="get" action="{% url 'finalapp:searchdata' %}" style="margin-left:275px;margin-top:20px;max-width:400px">
               {%  csrf_token %}
               <input type="text" placeholder="Search.." name="searchword">
               <button type="submit"><i class="fa fa-search"></i></button>
               </form>
               <nav id="mainav" class="fl_right">
                  <ul class="clear">
                     <li><a href="{% url 'index' %}">Home</a></li>
                     <li><a href="#">About</a></li>
                     <li class="active">
                        <a class="drop" href="#">Categories</a>
                        <ul>
                           <li><a href="#">Fashion</a></li>
                           <li><a href="#">Nature</a></li>
                           <li><a href="#">Wildlife</a></li>
                           <li><a href="#">Sports</a></li>
                           <li><a href="{% url 'myapp:category' %}">+More</a></li>
                        </ul>
                     </li>
                  </ul>
               </nav>
            </header>
         </div>
      </div>
      <div class="wrapper row2">
         <div id="breadcrumb" class="hoc clear">
            <ul>
               <li><a href="{% url 'index' %}">Home</a></li>
               <li><a href="{% url 'myapp:category' %}">Categories</a></li>
               <li><a href="#">Search</a></li>
            </ul>
         </div>
      </div>
      <div class="wrapper row3">
         <main class="hoc container clear">
            <div class="content">
               <p style="font-family:verdana;font-size:25px">Search results {{value}}</p>
               <!-- ===================================Photo Grids ============================ -->
               <div class="container mt-5" style="text-align: center">
                <div class="row">
                    {% for item in items %}
                    <div class="col-md-3 mt-5">
                        <img src="{{ item.image.url }}" alt="{{item.user}}" class="image" id="id{{ forloop.counter }}" name="img{{ forloop.counter }}"
                             onclick="popup('myModal', 'id{{ forloop.counter }}', 'img01', 'download_img', '{{ item.image.url }}','user',
                                             '{% url 'myapp:countlikes' item.image %}','li',
                                              '{% url 'myapp:user' item.user.id %}', '{{ item.likes }}')">
                    </div>
                    {% endfor %}

                </div>
            </div>

            <div id="myModal" class="container modal" style="width: 100%; height: 100%;">

                <div class="row">
                    <div class="col-md-8">
                        <img class="modal-content" id="img01">
                    </div>
                    <span class="close">&times</span>
                    <div class="col-sm-4">
                        <div class="btn-group-vertical">

                                <button class="btn btn-success">
                                    <a id="download_img" style="color: black; text-decoration: none" download>
                                        Free Download
                                    </a>
                                </button>

                            <br>
                            <form id="li" method="get">
                                {% if user.is_authenticated %}
                                <button class="btn btn-success">
                                    <span class="glyphicon glyphicon-thumbs-up"></span>
                                    Like &nbsp
                                    (<span id="likes"></span>)
                                </button>
                                {% else %}
                                <button class="btn btn-success"  disabled><span class="glyphicon glyphicon-thumbs-up"></span> Like</button><br>
                                <p>please login to like</p>
                                {% endif %}
                            </form><br>
                            <p style="color:#7FFF00"> image by:
                                <a id="user"></a>
                            </p>
                        </div><br><br>


                        <p style="color:#7FFF00">Freestock License:</p>
                        <p><span class="glyphicon glyphicon-ok"></span>  free for personal and commercial use</p>
                        <p><span class="glyphicon glyphicon-ok"></span> You can modify the photos.</p>

                        <div class="col-xs-6>
                            <div class="follow" style="color:#7FFF00">Follow us:</div>
                            <ul class="faico clear">
                              <li><a class="fa fa-facebook-official" href="#"><i></i></a></li>
                              <li><a class="fa fa-instagram"  href="#"><i></i></a></li>
                              <li><a class="fa fa-twitter-square" href="#"><i></i></a></li>
                              <li><a class="fa fa-google-plus-square" href="#"><i></i></a></li>
                            </ul>
                        </div>

                    </div>

                </div>
            </div>
<!------------------------------------------------------------------------------------------------------------------------->
               <nav class="pagination">
                  {% if users.has_other_pages %}
                  <ul style="margin-left: 28%;">
                     {% if users.has_previous %}
                     <li><a href="?page={{ users.previous_page_number }}">&laquo; Previous</a></li>
                     {% else %}
                     <li class="disabled"></li>
                     {% endif %}
                     {% for i in users.paginator.page_range %}
                     {% if users.number == i %}
                     <li class="current"><strong>{{ i }}</strong></li>
                     {% else %}
                     <li><a href="?page={{ i }}">{{ i }}</a></li>
                     {% endif %}
                     {% endfor %}
                     {% if users.has_next %}
                     <li><a href="?page={{ users.next_page_number }}">Next &raquo;</a></li>
                     {% else %}
                     <li class="disabled"></li>
                     {% endif %}
                  </ul>
                  {% endif %}
               </nav>
            </div>
            <div class="clear"></div>
         </main>
      </div>
      <div class="wrapper row4 bgded overlay" style="background-color:#546e7a;">
        <footer id="footer" class="hoc clear">
          <div class="one_third first">
            <h6 class="title">CONTACT</h6>
            <ul class="faico clear">
              <li><a class="fa fa-facebook-official" href="#"><i></i></a></li>
              <li><a class="fa fa-instagram"  href="#"><i></i></a></li>
              <li><a class="fa fa-twitter-square" href="#"><i></i></a></li>
              <li><a class="fa fa-google-plus-square" href="#"><i></i></a></li>
            </ul>
          </div>
          <div class="one_third">
            <h6 class="title"></h6>
            <ul class="nospace linklist contact">
                    </ul>
          </div>
          <div class="one_third">
            <h6 class="title">Freestock.com</h6>
            <ul class="nospace linklist">
              <li>
                <article>
                  <h2 class="nospace font-x1"><a href="#">About</a></h2>
                  <p class="nospace">FreeStock.com is a website where a user can download free stock photos </p>
                </article>
              </li>
            </ul>
          </div>
        </footer>
      </div>
      <div class="wrapper row5">
        <div id="copyright" class="hoc clear">
          <p class="fl_left">Copyright &copy; 2018 - All Rights Reserved - <a href="#">freestock.com</a></p>
          </div>
      </div>
      <a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>


      <script src="{% static 'category/scripts/jquery.min.js' %}"></script>
      <script src="{% static 'category/scripts/jquery.backtotop.js' %}"></script>
      <script src="{% static 'category/scripts/jquery.mobilemenu.js' %}"></script>
   </body>
</html>